routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServi within a group which|
| contains the "web" middleware group. Now create something great!
|
*/
Route::post('/user/logout','Auth\LoginController@userLogout')->name('user.logout');
Route::post('/admin/logout','Auth\AdminLoginController@logout')->name('admin.logout');

//product routes
Route::resource('product', 'ProductController');
Route::get('product/deal/{id}/add',['as'=>'product.addDeal','uses'=>'ProductController@addDeal']);
Route::get('product/deal/{id}/remove',['as'=>'product.removeDeal','uses'=>'ProductController@removeDeal']);

//review routes
Route::get('review/create/{slug}',['as'=>'review.create', 'uses'=>'ReviewController@create'])->where('slug','[\w\d\-\_]+')->middleware('auth');
Route::patch('review/{id}',['as'=>'review.isApproved', 'uses'=>'ReviewController@isApproved']);
Route::resource('review','ReviewController')->except('create');
//comment routes
Route::resource('comment', 'CommentController');
//subproduct
Route::resource('subproduct','SubproductController');


//subreview routes
Route::get('subreview/create/{slug}',['as'=>'subreview.create', 'uses'=>'SubreviewController@create'])->where('slug','[\w\d\-\_]+')->middleware('auth');
Route::resource('subreview','SubreviewController')->except('create');

//pages routes
Route::get('products/{slug}',['as'=>'pages.single', 'uses'=>'PagesController@getSingle'])->where('slug','[\w\d\-\_]+');
Route::get('accessories/{slug}',['as'=>'accessories.single', 'uses'=>'PagesController@getAccessories'])->where('slug','[\w\d\-\_]+');
Route::get('category/{name}',['as'=>'category.single','uses'=>'PagesController@getCategory']);
Route::get('checkout',['as'=>'pages.checkout','uses'=>'PagesController@checkout'])->middleware('auth');
Route::get('/events',['as'=>'events','uses'=>'PagesController@getEvents']);
Route::get('/','PagesController@index')->name('index');
Route::get('/about','PagesController@about')->name('about');
Route::get('/deals','PagesController@deals')->name('deals');
Route::get('/services','PagesController@services')->name('services');
Route::get('/profile','PagesController@profile')->name('profile')->middleware('auth');
Route::any('/search','PagesController@search')->name('search');
Route::any('/contact','PagesController@contact')->name('contact');

//order
Route::post('/order',['as'=>'order.store','uses'=>'OrderController@store']);
Route::post('/order/details',['as'=>'order.details','uses'=>'OrderController@orderDetails'])->middleware('auth');
Route::get('/order/approve/{id}','OrderController@isApproved')->name('order.approve');

Route::resource('store', 'StoreController');
Route::resource('category','CategoryController');

//cart routes
Route::get('cart/create/{slug}',['as'=>'cart.create','uses'=>'CartController@create'])->where('slug','[\w\d\-\_]+');
Route::get('cart/ajaxCreate/{slug}',['as'=>'cart.ajaxCreate','uses'=>'CartController@ajaxCreate'])->where('slug','[\w\d\-\_]+');
Route::get('cart/create/accessories/{slug}',['as'=>'cart.accessories','uses'=>'CartController@accessories'])->where('slug','[\w\d\-\_]+');
Route::get('cart/increase/{rowId}/{newQty}',['as'=>'cart.increase','uses'=>'CartController@increase']);
Route::get('cart/decrease/{rowId}/{newQty}',['as'=>'cart.decrease','uses'=>'CartController@decrease']);
Route::get('cart/remove/{rowId}',['as'=>'cart.remove','uses'=>'CartController@remove']);
Route::resource('cart','CartController')->except('create','index');
Route::get('/cart','CartController@index')->name('cart.index')->middleware('auth');

//admin routes
Route::get('/admin', 'AdminController@index')->name('admin.dashboard');
Route::prefix('admin')->group(function() {
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::get('/', 'AdminController@index')->name('admin.dashboard');
    Route::patch('review/{id}',['as'=>'review.isApproved', 'uses'=>'ReviewController@isApproved']);
    Route::resource('review','ReviewController')->except('create');
    Route::get('/orderItems',['as'=>'admin.orderItems','uses'=>'OrderController@allOrderItems']);
    Route::get('orders',['as'=>'orders.index','uses'=>'orderController@index'])->middleware('auth:admin');
    Route::delete('/orders/{id}',['as'=>'orders.destroy','uses'=>'orderController@destroy'])->middleware('auth:admin');
    Route::get('orders/approve/{id}',['as'=>'orders.approve','uses'=>'orderController@isApproved'])->middleware('auth:admin');

});

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    public function subproduct(){
        return $this->hasMany('App\Subproduct');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Product;
use Illuminate\Http\Request;
use Intervention\Image\Facades\Image;
use Illuminate\Support\Facades\Session;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth:admin');
    }

    public function index()
    {
        $products = Product::orderBy('id','dsec')->paginate(12);

        return view('product.index')->withProducts($products);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $category = Category::all();
        return view('product.add')->withCategory($category);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            //validating Code Goes Here.
        ]);
        $product = new Product();
        $product->name = $request->name;
        $product->description = $request->description;
        $product->category_id = $request->category_id;
        $product->unit_price = $request->unit_price;
        $product->best_deal = 0;
        $product->unit_weight = $request->unit_weight;
        $product->discount = $request->discount;
        //needs to be changed
        //$product->slug = generate slug from title
        $product->quantity = $request->quantity;
        $product->supplier_id = 10;

        //Gemerating unique slug

        $slug = str_slug("$request->name",'-');
        $newSlug = $slug.'-'.time();

        $product->slug = $newSlug;
        if($request->hasFile('images')){
            $image = $request->file('images');
            $filename = time() . '.' . $image->getClientOriginalExtension();
            $location = public_path('images/' . $filename);
            Image::make($image)->resize(720,405)->save($location);
            $product->images = $filename;
        }
        $product->save();
        Session::flash('message','Product is added succesfully');
        return redirect()->route('product.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = Product::whereId($id)->first();

        return view('product.show')->withProduct($product);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::find($id);
        $category = Category::all();

        return view('product.edit')->withProduct($product)->withCategory($category);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $product = Product::find($id);

        $this->validate($request,[
            //validating Code Goes Here.
        ]);

        $product->name = $request->input('name');
        $product->category_id = $request->input('category_id');
        $product->description = $request->input('description');
        $product->unit_price = $request->input('unit_price');
        $product->unit_weight = $request->input('unit_weight');
        $product->quantity = $request->input('quantity');
        $product->discount = $request->input('discount');
        if($request->hasFile('images')){
            $image = $request->file('images');
            $filename = time() . '.' . $image->getClientOriginalExtension();
            $location = public_path('images/' . $filename);
            Image::make($image)->resize(720,405)->save($location);
            $product->images = $filename;
        }
        $product->save();

        Session::flash('message',"$product->name is updated successfully");
        return redirect()->route('product.show',$product->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = Product::find($id);
        $product->delete();

        Session::flash('message','The Product is deleted.');
        return redirect()->route('product.index');
    }

    public function addDeal($id){
        $product = Product::find($id);
        $product->best_deal = 1;
        $product->save();
        Session::flash('message','The Product is added to the Best Deals list.');
        return redirect()->back();
    }
    public function removeDeal($id){
        $product = Product::find($id);
        $product->best_deal = 0;
        $product->save();
        Session::flash('message','The Product is removed to the Best Deals list.');
        return redirect()->back();
    }

}

resources/views/product/about.blade.php
@extends('main')

resources/views/product/add.blade.php
@extends('layouts.admin')
@section('stylesheet')
    <script src="{{ asset('js/parsley.min.js') }}"></script>
    @endsection
@section('title', 'Add Product')

@section('content')

    <div class="row">
        <div class="col-sm-8 col-sm-offset-4">
            <h3>Add New Product</h3>
            <hr>
            {!! Form::open(['route'=>'product.store','files'=>true, 'data-parsley-validate']) !!}
            {{--product name--}}
            {{Form::label('name','Name:')}}
            {{Form::text('name',null,["class"=>"form-control",'required'=>' ','maxlength'=>'100'])}}
            {{--//Product Category--}}
            {{Form::label('category_id','Category')}}
            <select class="form-control" name="category_id" style="margin-bottom: 10px" required="">
                @foreach($category as $category)
                    <option value="{{$category->id}}">{{$category->name}}</option>
                @endforeach
            </select>
            {{--//Product images--}}

            {{ Form::label('images','Add Product Image:') }}
            {{ Form::file('images') }}<br>
            {{--//Description--}}
            {{Form::label('description','Product Description:')}}
            {{Form::textarea('description',null,array('class'=>'form-control','required'=>'','minlength'=>'20','maxlength'=>'190'))}}
            {{--UNit Price--}}
            {{ Form::label('unit_price', 'Unit Price of the Product:') }}
            {{ Form::number('unit_price',null,['class'=>'form-control','required'=>'']) }}
            {{--unit weight--}}
            {{ Form::label('unit_weight', 'Unit Weight of the Product:') }}
            {{ Form::number('unit_weight',null,['class'=>'form-control','required'=>'']) }}
            {{--quantity--}}
            {{ Form::label('quantity', 'Total Quantity:') }}
            {{ Form::number('quantity',null,['class'=>'form-control','required'=>'']) }}
            {{--Discount--}}
            {{ Form::label('discount', 'Discounts if any:') }}
            {{ Form::number('discount',null,['class'=>'form-control']) }}

            <br>
            {{Form::submit('Add Product', array('class'=>'btn btn-success btn-lg btn-block'))}}
            {!! Form::close() !!}

        </div>
    </div>

    @endsection

resources/views/product/edit.blade.php
@extends('layouts.admin')
@section('stylesheet')
    <script src="{{ asset('js/parsley.min.js') }}"></script>
@endsection
@section('title','Product Edit')

@section('content')
    <div class="row">
        <div class="col-md-2">
            <a href="{{ route('product.index') }}" class="btn btn-info">All Products</a>
        </div>
        <div class="col-md-2 offset-md-3">
            <a href="{{ route('product.show',$product->id) }}" class="btn btn-primary">View Product</a>
        </div>
        <div class="col-md-2 offset-md-3">
            {{ Form::open(['route'=>["product.destroy",$product->id],'method'=>'DELETE']) }}
            {{ Form::submit('Delete',['class'=>'btn btn-danger']) }}
            {{ Form::close() }}
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <h3>Edit the Product Information</h3>
            <hr>
            {!! Form::model($product,['route'=>['product.update',$product->id],'files'=>true,'method'=>'PUT', 'data-parsley-validate']) !!}
            {{--product name--}}
            {{Form::label('name','Name:')}}
            {{Form::text('name',null,["class"=>"form-control",'required'=>' ','maxlength'=>'255'])}}
            {{--//Product Category--}}
            {{Form::label('category_id','Category')}}
            <select class="form-control" name="category_id" style="margin-bottom: 10px" required="">
                @foreach($category as $category)
                    <option value="{{$category->id}}" @if($product->category_id==$category->id)
                                                          selected
                        @endif>{{$category->name}}</option>
                @endforeach
            </select>
            {{--//Product images--}}
            {{ Form::label('images','Add Product Image:') }}
            {{ Form::file('images') }}<br>
            {{--//Description--}}
            {{Form::label('description','Product Description:')}}
            {{Form::textarea('description',null,array('class'=>'form-control','required'=>'','minlength'=>'30','maxlength'=>'190'))}}
            {{--UNit Price--}}
            {{ Form::label('unit_price', 'Unit Price of the Product:') }}
            {{ Form::number('unit_price',null,['class'=>'form-control','required'=>'']) }}
            {{--unit weight--}}
            {{ Form::label('unit_weight', 'Unit Weight of the Product:') }}
            {{ Form::number('unit_weight',null,['class'=>'form-control','required'=>'']) }}
            {{--quantity--}}
            {{ Form::label('quantity', 'Total Quantity:') }}
            {{ Form::number('quantity',null,['class'=>'form-control','required'=>'']) }}
            {{--Discount--}}
            {{ Form::label('discount', 'Discounts if any:') }}
            {{ Form::number('discount',null,['class'=>'form-control']) }}

            <br>
            {{Form::submit('Add Product', array('class'=>'btn btn-success btn-lg btn-block'))}}
            {!! Form::close() !!}

        </div>
    </div>
    @endsection

resources/views/product/index.blade.php
@extends('layouts.admin')
@section('title','All Products List')
@section('breadcrumb','All Products')

@section('content')
    <div class="row">
        <div class="col-md-2">
            <a href="{{ route('product.create') }}" class="btn btn-primary">Add New Product</a>
        </div>
        <div class="col-md-2 offset-md-8">
            <a href="" class="btn btn-primary">View Orders</a>
        </div>
    </div>
    <br>
<div class="row">
    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Name</th>
            <th scope="col">Quantity</th>
            <th scope="col">Price</th>
            <th scope="col">Action</th>
        </tr>
        </thead>

        <tbody>
        @foreach($products as $product)
        <tr>
            <th scope="row">{{ $product->id }}</th>
            <td>{{ $product->name }}</td>
            <td>{{ $product->quantity }}</td>
            <td>{{ $product->unit_price }}</td>
            <td>
                <div class="row">
                    @if(!empty($product->best_deal))
                        @if($product->best_deal == 1)
                            <a href="{{ route('product.removeDeal',$product->id) }}" class="btn btn-info">Remove From BestDeal</a>

                        @endif
                    @else
                        <a href="{{ route('product.addDeal',$product->id) }}" class="btn btn-info">Add to BestDeal</a>
                    @endif
                        <a href="{{ route('product.show',$product->id) }}" class="btn btn-info" style="margin:0px 0px 0px 10px;">View</a>
                <a href="{{ route('product.edit',$product->id) }}" class="btn btn-primary" style="margin:0px 10px 0px 10px;">Edit</a>
                {{ Form::open(['route'=>["product.destroy",$product->id],'method'=>'DELETE']) }}
                {{ Form::submit('Delete',['class'=>'btn btn-danger']) }}
                {{ Form::close() }}


                </div>
            </td>
        </tr>
            @endforeach
        </tbody>
    </table>
</div>

    @endsection

resources/views/product/show.blade.php
@extends('layouts.admin')
@section('title',"$product->name")
@section('content')
    <div class="col-xs-8">
        <div class="row">
            <div class="col-md-8">
                <h1>{{ $product->name }}</h1>
                <img src="{{ url('images/'.$product->images)}}" alt="Image">
                <hr>
            </div>

            <div class="col-md-4">
                <p>Description: {{ $product->description }}<br>
                    {{ url('images/'.$product->images)}}</p>
            </div>

        </div>


    </div>

    @endsection