routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServi within a group which|
| contains the "web" middleware group. Now create something great!
|
*/
Route::post('/user/logout','Auth\LoginController@userLogout')->name('user.logout');
Route::post('/admin/logout','Auth\AdminLoginController@logout')->name('admin.logout');

//product routes
Route::resource('product', 'ProductController');
Route::get('product/deal/{id}/add',['as'=>'product.addDeal','uses'=>'ProductController@addDeal']);
Route::get('product/deal/{id}/remove',['as'=>'product.removeDeal','uses'=>'ProductController@removeDeal']);

//review routes
Route::get('review/create/{slug}',['as'=>'review.create', 'uses'=>'ReviewController@create'])->where('slug','[\w\d\-\_]+')->middleware('auth');
Route::patch('review/{id}',['as'=>'review.isApproved', 'uses'=>'ReviewController@isApproved']);
Route::resource('review','ReviewController')->except('create');
//comment routes
Route::resource('comment', 'CommentController');
//subproduct
Route::resource('subproduct','SubproductController');


//subreview routes
Route::get('subreview/create/{slug}',['as'=>'subreview.create', 'uses'=>'SubreviewController@create'])->where('slug','[\w\d\-\_]+')->middleware('auth');
Route::resource('subreview','SubreviewController')->except('create');

//pages routes
Route::get('products/{slug}',['as'=>'pages.single', 'uses'=>'PagesController@getSingle'])->where('slug','[\w\d\-\_]+');
Route::get('accessories/{slug}',['as'=>'accessories.single', 'uses'=>'PagesController@getAccessories'])->where('slug','[\w\d\-\_]+');
Route::get('category/{name}',['as'=>'category.single','uses'=>'PagesController@getCategory']);
Route::get('checkout',['as'=>'pages.checkout','uses'=>'PagesController@checkout'])->middleware('auth');
Route::get('/events',['as'=>'events','uses'=>'PagesController@getEvents']);
Route::get('/','PagesController@index')->name('index');
Route::get('/about','PagesController@about')->name('about');
Route::get('/deals','PagesController@deals')->name('deals');
Route::get('/services','PagesController@services')->name('services');
Route::get('/profile','PagesController@profile')->name('profile')->middleware('auth');
Route::any('/search','PagesController@search')->name('search');
Route::any('/contact','PagesController@contact')->name('contact');

//order
Route::post('/order',['as'=>'order.store','uses'=>'OrderController@store']);
Route::post('/order/details',['as'=>'order.details','uses'=>'OrderController@orderDetails'])->middleware('auth');
Route::get('/order/approve/{id}','OrderController@isApproved')->name('order.approve');

Route::resource('store', 'StoreController');
Route::resource('category','CategoryController');

//cart routes
Route::get('cart/create/{slug}',['as'=>'cart.create','uses'=>'CartController@create'])->where('slug','[\w\d\-\_]+');
Route::get('cart/ajaxCreate/{slug}',['as'=>'cart.ajaxCreate','uses'=>'CartController@ajaxCreate'])->where('slug','[\w\d\-\_]+');
Route::get('cart/create/accessories/{slug}',['as'=>'cart.accessories','uses'=>'CartController@accessories'])->where('slug','[\w\d\-\_]+');
Route::get('cart/increase/{rowId}/{newQty}',['as'=>'cart.increase','uses'=>'CartController@increase']);
Route::get('cart/decrease/{rowId}/{newQty}',['as'=>'cart.decrease','uses'=>'CartController@decrease']);
Route::get('cart/remove/{rowId}',['as'=>'cart.remove','uses'=>'CartController@remove']);
Route::resource('cart','CartController')->except('create','index');
Route::get('/cart','CartController@index')->name('cart.index')->middleware('auth');

//admin routes
Route::get('/admin', 'AdminController@index')->name('admin.dashboard');
Route::prefix('admin')->group(function() {
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::get('/', 'AdminController@index')->name('admin.dashboard');
    Route::patch('review/{id}',['as'=>'review.isApproved', 'uses'=>'ReviewController@isApproved']);
    Route::resource('review','ReviewController')->except('create');
    Route::get('/orderItems',['as'=>'admin.orderItems','uses'=>'OrderController@allOrderItems']);
    Route::get('orders',['as'=>'orders.index','uses'=>'orderController@index'])->middleware('auth:admin');
    Route::delete('/orders/{id}',['as'=>'orders.destroy','uses'=>'orderController@destroy'])->middleware('auth:admin');
    Route::get('orders/approve/{id}',['as'=>'orders.approve','uses'=>'orderController@isApproved'])->middleware('auth:admin');

});

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

resources/views/admin/index.blade.php
@extends('layouts.admin')
@section('title','Dashboard')
@section('breadcrumb','Overview')
@section('content')

    <div class="row">
        <div class="col-xl-3 col-sm-6 mb-3">
            <div class="card text-white bg-primary o-hidden h-100">
                <div class="card-body">
                    <div class="card-body-icon">
                        <i class="fas fa-fw fa-comments"></i>
                    </div>
                    <div class="mr-5">26 New Products!</div>
                </div>
                <a class="card-footer text-white clearfix small z-1" href="{{ route('product.index') }}">
                    <span class="float-left">View Details</span>
                    <span class="float-right">
                    <i class="fas fa-angle-right"></i>
                  </span>
                </a>
            </div>
        </div>
        <div class="col-xl-3 col-sm-6 mb-3">
            <div class="card text-white bg-warning o-hidden h-100">
                <div class="card-body">
                    <div class="card-body-icon">
                        <i class="fas fa-fw fa-list"></i>
                    </div>
                    <div class="mr-5">11 New Reviews!</div>
                </div>
                <a class="card-footer text-white clearfix small z-1" href="{{ route('review.index') }}">
                    <span class="float-left">View Details</span>
                    <span class="float-right">
                    <i class="fas fa-angle-right"></i>
                  </span>
                </a>
            </div>
        </div>
        <div class="col-xl-3 col-sm-6 mb-3">
            <div class="card text-white bg-success o-hidden h-100">
                <div class="card-body">
                    <div class="card-body-icon">
                        <i class="fas fa-fw fa-shopping-cart"></i>
                    </div>
                    <div class="mr-5">123 New Orders!</div>
                </div>
                <a class="card-footer text-white clearfix small z-1" href="#">
                    <span class="float-left">View Details</span>
                    <span class="float-right">
                    <i class="fas fa-angle-right"></i>
                  </span>
                </a>
            </div>
        </div>
        <div class="col-xl-3 col-sm-6 mb-3">
            <div class="card text-white bg-danger o-hidden h-100">
                <div class="card-body">
                    <div class="card-body-icon">
                        <i class="fas fa-fw fa-life-ring"></i>
                    </div>
                    <div class="mr-5">13 New Tickets!</div>
                </div>
                <a class="card-footer text-white clearfix small z-1" href="#">
                    <span class="float-left">View Details</span>
                    <span class="float-right">
                    <i class="fas fa-angle-right"></i>
                  </span>
                </a>
            </div>
        </div>
    </div>

    {{--<!-- Area Chart Example-->--}}
    {{--<div class="card mb-3">--}}
        {{--<div class="card-header">--}}
            {{--<i class="fas fa-chart-area"></i>--}}
            {{--Area Chart Example</div>--}}
        {{--<div class="card-body">--}}
            {{--<canvas id="myAreaChart" width="100%" height="30"></canvas>--}}
            {{--<canvas id="myAreaChart" width="100%" height="30"></canvas>--}}

        {{--</div>--}}
        {{--<div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>--}}
    {{--</div>--}}
    <!-- DataTables Example -->
    <div class="card mb-3">
        <div class="card-header">
            <i class="fas fa-table"></i>
            Users</div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Joining date</th>
                        <th>Mobile</th>
                        <th>Address</th>
                    </tr>
                    </thead>
                    <tfoot>
                    <tr>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Joining date</th>
                        <th>Mobile</th>
                        <th>Address</th>
                    </tr>
                    </tfoot>
                    <tbody>
                    @foreach($users as $user)
                    <tr>
                        <td>{{ $user->name }}</td>
                        <td>{{ $user->email }}</td>
                        <td>{{ $user->created_at}}</td>
                            @foreach($user->order as $order)
                            <td>{{ $order->mobile }}</td>
                            <td>{{ $order->address }}</td>
                            @break
                            @endforeach
                    </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>


    @endsection

resources/views/admin/orderItems.blade.php
@extends('layouts.admin')
@section('title','Items on orders')
@section('content')

    <div class="row">
        <table class="table table-hover">
            <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Name</th>
                <th scope="col">Quantity</th>
                <th scope="col">Product ID</th>
                <th scope="col">Action</th>
            </tr>
            </thead>

            <tbody>
            @foreach($items as $items)
                <tr>
                    <th scope="row">{{ $items->id }}</th>
                    <td>{{ $items->product_name }}</td>
                    <td>{{ $items->quantity }}</td>
                    <td><a href="{{ route('product.show',$items->product_id) }}">{{ $items->product_id }}</a></td>
                    <td>
                        <div class="row">
                            {{--@if($items->isApproved == 0)--}}
                                {{--{{ Form::open(['route'=>["items.isApproved",$items->id],'method'=>'PATCH']) }}--}}
                                {{--{{ Form::submit('Approve',['class'=>'btn btn-primary']) }}--}}
                                {{--{{ Form::close() }}--}}
                            {{--@endif--}}
                            {{--{{ Form::open(['route'=>["items.destroy",$items->id],'method'=>'DELETE']) }}--}}
                            {{--{{ Form::submit('Delete',['class'=>'btn btn-danger']) }}--}}
                            {{--{{ Form::close() }}--}}
                        </div>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>

    @endsection